version: '3'

silent: true

includes:
  version:
    taskfile: .taskfile/version.yml
  rust:
    taskfile: .taskfile/rust.yml
  utils:
    taskfile: .taskfile/utils.yml
  agent:
    taskfile: .taskfile/agent.yml

tasks:
  run:
    cmds:
      - cargo run --bin doclayer-test -- {{.CLI_ARGS}}